// Ré-export ciblé des icônes RemixIcon utilisées dans Logbook, pour garder
// une liste explicite et éviter d'importer tout le catalogue par erreur.
// Catalogue complet : https://remixicon.com
//
// Ajouter une icône : l'importer ici depuis '@remixicon/react', puis
// l'utiliser via `import { RiMicLine } from '@/icons'` (ou chemin relatif).

export {
  RiMicLine,
  RiMicFill,
  RiCheckboxCircleLine,
  RiCheckboxCircleFill,
  RiErrorWarningLine,
  RiVolumeUpLine,
  RiPlayCircleLine,
  RiFileTextLine,
  RiBarChartLine,
  RiUserLine,
  RiCloseLine,
  RiArrowRightLine,
  RiArrowLeftLine,

  // Flèches & chevrons
  RiArrowUpLine,
  RiArrowDownLine,
  RiArrowUpSLine,
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiArrowDropUpLine,
  RiArrowDropDownLine,
  RiArrowDropLeftLine,
  RiArrowDropRightLine,
  RiArrowLeftUpLine,
  RiArrowRightUpLine,
  RiArrowLeftDownLine,
  RiArrowRightDownLine,
  RiArrowUpLongLine,
  RiArrowDownLongLine,
  RiArrowLeftLongLine,
  RiArrowRightLongLine,
  RiArrowLeftUpLongLine,
  RiArrowRightUpLongLine,
  RiArrowLeftDownLongLine,
  RiArrowRightDownLongLine,
  RiArrowLeftRightLine,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,

  // Actions & saisie
  RiAddLine,
  RiAddLargeLine,
  RiCheckLine,
  RiCloseLargeLine,
  RiPencilLine,
  RiEdit2Line,
  RiDeleteBinLine,
  RiUploadLine,
  RiUpload2Line,
  RiUploadCloudLine,
  RiDownload2Line,
  RiRefreshLine,
  RiLoopLeftLine,
  RiLoopRightLine,
  RiRestartLine,
  RiAnticlockwiseLine,
  RiForward30Line,
  RiReplay30Line,
  RiPlayLine,
  RiPlayLargeLine,
  RiPauseLine,
  RiPauseLargeLine,
  RiPauseCircleLine,
  RiStopCircleLine,
  RiSquareLine,
  RiSearchLine,
  RiSendPlaneLine,
  RiThumbUpLine,

  // Statuts, alertes & feedback
  RiAlarmLine,
  RiSparklingLine,
  RiEmotionLine,
  RiEmotionNormalLine,
  RiEmotionLaughFill,
  RiEmotionSadLine,
  RiEmotionUnhappyLine,
  RiEmotion2Line,
  RiStarLine,
  RiVerifiedBadgeLine,
  RiShieldCheckLine,
  RiFocusLine,
  RiTrophyLine,

  // Communication & notifications
  RiMailLine,
  RiChat3Line,
  RiQuestionLine,
  RiQuestionAnswerLine,
  RiNotificationLine,
  RiNotificationOffLine,
  RiNotificationSnoozeLine,
  RiMegaphoneLine,
  RiMicAiLine,
  RiHeadphoneLine,
  RiCustomerServiceLine,
  RiEqualizerLine,

  // Personnes & compte
  RiUserAddLine,
  RiUserSmileLine,
  RiAccountCircleLine,
  RiGroupLine,
  RiTeamLine,
  RiHeartLine,

  // Navigation & structure
  RiHomeLine,
  RiHomeFill,
  RiInformationLine,
  RiDashboardLine,
  RiMenuLine,
  RiMoreLine,
  RiMore2Line,
  RiMapPinLine,
  RiTimeLine,
  RiCalendarLine,
  RiLightbulbLine,
  RiLineChartLine,
  RiPriceTagLine,
  RiStickyNoteAddLine,
  RiFileCopyLine,
  RiFileCheckLine,
  RiQrCodeLine,
  RiKeyLine,
  RiLockLine,
  RiLogoutBoxLine,
  RiSettingsLine,
  RiSettings3Line,
  RiEyeLine,
  RiEyeOffLine,
  RiEyeCloseLine,

  // Partage & réseaux
  RiShare2Line,
  RiLinksLine,
  RiInstagramLine,
  RiLinkedinLine,
  RiLinkedinBoxFill,
  RiYoutubeLine,

  // Texte & IA
  RiText,
  RiAiGenerateText,
} from '@remixicon/react';
